name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.11" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-${{ matrix.python-version }}-

      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m pytest -q

      - name: Build Docker image
        run: docker build -t privacy-layer:ci .

      - name: Docker smoke test (good dataset)
        run: |
          docker run --rm \
            -v "$PWD:/app" -w /app \
            privacy-layer:ci \
            --input data/sample_transactions.csv \
            --out out_ci_good \
            --policy configs/fintech_default.json
          test -f out_ci_good/dataset_masked.csv
          test -f out_ci_good/governance_log.json

      - name: Docker smoke test (bad dataset -> quarantine)
        run: |
          docker run --rm \
            -v "$PWD:/app" -w /app \
            privacy-layer:ci \
            --input data/sample_transactions_bad.csv \
            --out out_ci_bad \
            --policy configs/fintech_default.json || true
          test -f out_ci_bad/quarantine_raw.csv
          test -f out_ci_bad/quarantine_masked.csv

      - name: Upload artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-outputs
          path: |
            out_ci_good/**
            out_ci_bad/**