name: CI

on:
  push:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Generate outputs inside CI (no pre-existing out/ in repo)
      - name: Run demo (generate outputs)
        run: |
          python -m cli.process \
            --input data/sample_transactions.csv \
            --out out_ci \
            --policy configs/fintech_default.json

      - name: Verify outputs
        run: python audit/verify.py out_ci configs/fintech_default.json

      - name: Upload CI outputs (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-outputs-${{ matrix.python-version }}
          path: |
            out_ci/**